# Polynomial regression
It needs the datascience package from Berkeley<br>
https://github.com/data-8/datascience<br>
Installation is 'pip install datascience'

In [ ]:

#Please run this first
import sys
import numpy as np

from datascience import *
from sklearn.linear_model  import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

In [ ]:
# Got the datapoints from
# https://johnstonmd.wordpress.com/teaching/math-178-spring-2017/
x = np.array([16, 17, 23, 25, 28, 31, 40, 48, 54, 67]).reshape((-1, 1))
y = np.array([180, 163, 172, 168, 165, 156, 153, 144, 139, 130])
print(x)
print(y)

### Numpy calculate regression with a two dimensional array x.
### For our table we map the two dimensional array to a one dimentional array.

In [ ]:
x_one_dimensional = [_[0] for _ in x]
x_one_dimensional

In [ ]:
table = Table().with_columns(
    'Age', x_one_dimensional,
    'Heart rate', y
)
table

In [ ]:
table.scatter('Age')

In [ ]:
def polynomial_regression(x, y, degree_my = 1):
  """
  Return R^2, coefficients and the interception
  
  polynomial_regression(x, y, degree_my = 1) -> (r_sq, coefficients, interception)

  Parameters
  ----------
  x: np.array, regressors
  y: np.array, predictors
  degree: int, optional, default 1, the degree of the model function
  
  Examples
  --------
  >>> x = np.array([16, 17, 23, 25, 28, 31, 40, 48, 54, 67]).reshape((-1, 1))
  >>> y = np.array([180, 163, 172, 168, 165, 156, 153, 144, 139, 130])

  >>> x
  array([[16],
         [17],
         [23],
         [25],
         [28],
         [31],
         [40],
         [48],
         [54],
         [67]])
  >>> y
  array([180, 163, 172, 168, 165, 156, 153, 144, 139, 130])
  >>> polynomial_regression(x, y)
  (0.9141779810921304, array([-0.88693692]), 187.95409848808737)
  >>> polynomial_regression(x, y, 2)
  (0.9147602910606555, array([-1.01045344,  0.00153909]), 189.99421074646295)
  >>> polynomial_regression(x, y, 5)
  (0.9184131002053144, array([ 7.73620330e+00, -4.45581354e-01,  1.08361046e-02, -1.26584517e-04,
          5.75609467e-07]), 126.4417938766303)
  >>> 
  """
  transformer = PolynomialFeatures(degree = degree_my, include_bias = False)
  transformer.fit(x)
  x_ = transformer.transform(x)

  model = LinearRegression().fit(x_, y)
  
  coefficient_of_determination = model.score(x_, y)
  interception = model.intercept_
  coefficients = model.coef_

  return (coefficient_of_determination, coefficients, interception)

def linear_regression(x, y):
  """
  Returns R^2, slope and interception
  """
  # Reusing the existing 'general' polynomial_regression function
  return polynomial_regression(x, y, 1) 

linear_regression(x, y)

In [ ]:
r_sq, coefficients, interception = linear_regression(x, y)
print('R^2: ', r_sq)
print('coefficients: ', coefficients)
print('intersection: ', interception)

In [ ]:
prediction_function = lambda age: coefficients[0] * age + interception
print(prediction_function)
age = 31
print('your predicted HR is %d' % prediction_function(age))

In [ ]:
prediction_array = prediction_function(table.column('Age'))
prediction_array

In [ ]:
# Shows only the first five elements in the array
prediction_array[:5]

In [ ]:
table = table.with_column(
    'Linear Prediction', prediction_array
)
table

In [ ]:
table.scatter(0)

In [ ]:
slope = coefficients[0]
print('slope: ', slope)

print('The linear regression model is y = %.2f*x + %.2f' % (slope, interception))

age = int(input('what is your age: '))
print('your recomended HR is %d' % (prediction_function(age)))
print('this is %.2f percent accurate' %( r_sq * 100) )

In [ ]:
def quadratic_regression(x, y):
  """
  Returning R^2, coefficients and the interceptions as a size three tupple.
  """
  return polynomial_regression(x, y, 2)

r_sq, coefficients, interception = quadratic_regression(x, y)
print('R^2: ', r_sq)
print('coefficients: ', coefficients)
print('intersection: ', interception)

In [ ]:
prediction_function = \
  lambda age: sum( [coefficients[i] * age**(i + 1) for i in range(len(coefficients))] ) + interception
prediction_function

In [ ]:
quadratic_prediction_array = prediction_function(table.column('Age'))
quadratic_prediction_array

In [ ]:
table = table.with_column(
    'Quadratic Prediction', quadratic_prediction_array
)
table

In [ ]:
table.scatter(0)

In [ ]:
def cubic_regression(x, y):
  """
  Returning R^2, coefficients and the interceptions as a size three tupple.
  """
  return polynomial_regression(x, y, 3)

In [ ]:
r_sq, coefficients, interception = cubic_regression(x, y)
print('R^2: ', r_sq)
print('coefficients: ', coefficients)
print('intersection: ', interception)

In [ ]:
prediction_function = \
  lambda age: sum( [coefficients[i] * age**(i + 1) for i in range(len(coefficients))] ) + interception
prediction_function

In [ ]:
table = table.with_column(
    'Cubic prediction', prediction_function(table.column(0))
)
table

In [ ]:
table.scatter(0)

In [ ]:
def top_polynomial_regressions(x, y, max_degree, top = 10):
  """
  Print out the best polynomial regressions with the highest Q^2 in a sorted list 
  
  Parameters
  ----------
  x: np.array, regressors
  y: np.array, predictors
  max_degree: int, the degree of the model function
  top: int, number of rows printed from the sorted regressions
  

  Examples
  --------
  >>> x = np.array([16, 17, 23, 25, 28, 31, 40, 48, 54, 67]).reshape((-1, 1))
  >>> y = np.array([180, 163, 172, 168, 165, 156, 153, 144, 139, 130])
  >>> x
  array([[16],
         [17],
         [23],
         [25],
         [28],
         [31],
         [40],
         [48],
         [54],
         [67]])
  >>> y
  array([180, 163, 172, 168, 165, 156, 153, 144, 139, 130])
  >>> top_polynomial_regressions(x, y, 20)
  the top 10 polynomial regressions are
  0.9920 Q^2 with degree 7
  0.9838 Q^2 with degree 8
  0.9741 Q^2 with degree 9
  0.9333 Q^2 with degree 18
  0.9332 Q^2 with degree 17
  0.9330 Q^2 with degree 19
  0.9330 Q^2 with degree 15
  0.9327 Q^2 with degree 16
  0.9326 Q^2 with degree 14
  0.9319 Q^2 with degree 13
  >>> top_polynomial_regressions(x, y, 20, 3)
  the top 3 polynomial regressions are
  0.9920 Q^2 with degree 7
  0.9838 Q^2 with degree 8
  0.9741 Q^2 with degree 9
  >>> 
  """
  sorted_polynomial_regressions = lambda x,y, max_degree: sorted([(polynomial_regression(x,y,i)[0], i) for i in range(2, max_degree)], reverse = True)

  print('the top %d polynomial regressions are' %top)
  for regression in sorted_polynomial_regressions(x, y, max_degree)[:top]:
    print('%.4f Q^2 with degree %d' %(regression[0], regression[1]))


In [ ]:
top_polynomial_regressions(x, y, 100, 5)

In [ ]:
top_polynomial_regressions(x, y, 100)

In [ ]:
table

In [ ]:
help(polynomial_regression)

In [ ]:
r_sq, coefficients, interception = polynomial_regression(x, y, 7)
print('R^2: ', r_sq)
print('coefficients: ', coefficients)
print('intersection: ', interception)

In [ ]:
prediction_function = \
  lambda age: sum( [coefficients[i] * age**(i + 1) for i in range(len(coefficients))] ) + interception
prediction_function

In [ ]:
table = table.with_column(
    '7th degree Prediction', prediction_function(table.column(0))
)
table

In [ ]:
table.scatter(0)